Update
Artsav23/SocialNetwork pull request #1
Opened 2022-06-27 19:55 UTC by Artsav23

2022-06-27 19:58 UTC, mokhaneugene commented
What is "Update" at the title of pr (pull request)?
Write the name of the changes at this pr pls

2022-06-27 20:21 UTC, mokhaneugene requested changes

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +    var publicationModel= mutableListOf<PublicationModel>()
I think, you should set private at the 10 line, not at the 9 line, but mb(maybe) it's incorrect

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>      class ViewHolder(item:View):RecyclerView.ViewHolder(item) {
Why did you create the class inside other class?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +            binding.imageView3.setImageResource(publicationModel.imageId)
what is imageView3? Change the name of this view

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +            binding.comments.text=publicationModel.comment
try to use the type of the view at the naming, for example, when you create a textView for the title, try to use titleTextView

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>      interface Listener{
what is interface?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>      lateinit var binding: ActivityAddPudlicationBinding
set the empty line pls

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>      var images=Images()
why it isn't private?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>              num++
fix the tabulation pls

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>          binding.next.setOnClickListener {
can u (you) set this logic at other function?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>              num--
fix the tabulation pls

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>          binding.cancel.setOnClickListener {
can u set this logic at other function?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>              binding.imageView.setImageResource(images.images[num])
can u set this logic at other function?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
> +                val data =Intent()
set the space between = and Intent()

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
> +    private fun setSupportActionBar(){
set the space between () and {

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
> +        supportActionBar?.title="Add Publication"
supportActionBar?.title = "Add Publication"

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>      lateinit var launcher: ActivityResultLauncher<Intent>
can it been private?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>      lateinit var binding: ActivityMainBinding
can it been private?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>      var adapter=Adapter(this)
can it been private?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +    var data= mutableListOf<PublicationModel>()
can it been private?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>          launcher=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){
can it locate at other function?

2022-06-27 20:21 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +    private fun initRecyclerView(){
private fun initRecyclerView() {

2022-06-27 20:59 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>      interface Listener{
хрень позволяющая делать действия когда твое вью открыто на другом вью, в данном случае она позволяет мне при нажатии на публикацию перейти на отдельную страницу с одним вью

2022-06-27 21:04 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>          binding.next.setOnClickListener {
не понял

2022-06-27 21:12 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +    var publicationModel= mutableListOf<PublicationModel>()
сделал

2022-06-27 21:12 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +            binding.imageView3.setImageResource(publicationModel.imageId)
сделал

2022-06-27 21:12 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +            binding.comments.text=publicationModel.comment
сделал

2022-06-27 21:13 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>      lateinit var binding: ActivityAddPudlicationBinding
сделал

2022-06-27 21:13 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>      var images=Images()
сделал

2022-06-27 21:13 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>              num++
сделал

2022-06-27 21:14 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>              num--
сделал

2022-06-27 21:14 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
>              binding.imageView.setImageResource(images.images[num])
сделал

2022-06-28 14:01 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +                    data.add(PublicationModel(it.data?.getStringExtra("imageId")?.toInt()!!,
работать не будет тогда

2022-06-28 14:03 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/OneView.kt
>  class OneView : AppCompatActivity() {
окно которое показывает публикацию в отдельном окне

2022-06-28 14:05 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +    private fun initRecyclerView(){
сделал

2022-06-28 14:06 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>              when(it.itemId){
сделал

2022-06-28 14:06 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>                 R.id.add->{
сделал

2022-06-28 14:06 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>                  if (it.resultCode== RESULT_OK){
done

2022-06-28 14:06 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +    var data= mutableListOf<PublicationModel>()
done

2022-06-28 14:06 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>      var adapter=Adapter(this)
done

2022-06-28 14:06 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>      lateinit var launcher: ActivityResultLauncher<Intent>
done

2022-06-28 14:07 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
> +    private fun setSupportActionBar(){
done

2022-06-28 17:39 UTC, mokhaneugene requested changes

2022-06-28 17:44 UTC, mokhaneugene requested changes

2022-06-28 17:44 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +                   val intent= Intent(this, AddPublication::class.java)
val intent =

2022-06-28 17:45 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
> +    private fun setSupportActionBar(){
пробел поставь

2022-06-29 11:27 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/OneView.kt
>      lateinit var binding: ActivityOneViewBinding
done

2022-06-29 11:39 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +                   val intent= Intent(this, AddPublication::class.java)
done

2022-06-29 11:39 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/ViewHolder.kt
> +    fun bind(publicationModel: PublicationModel, listener: Adapter.Listener){
done

2022-06-29 11:39 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/PublicationModel.kt
> +
done

2022-06-29 11:39 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/OneView.kt
> +        binding.commentsTextView.text=item.comment
done

2022-06-29 11:39 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
> +    fun next() {
done

2022-06-29 11:40 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/AddPublication.kt
> +    fun cancel() {
done

2022-06-29 11:40 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/OneView.kt
>          binding.comments.text=item.comment
done

2022-06-29 11:40 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/OneView.kt
>  class OneView : AppCompatActivity() {
done

2022-06-29 15:35 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
> +                    data.add(PublicationModel(it.data?.getStringExtra("imageId")?.toInt()!!,
done

2022-07-07 12:05 UTC, mokhaneugene approved these changes
Good work!

2022-07-11 14:24 UTC, merged