add few publication
Artsav23/SocialNetwork pull request #2
Opened 2022-07-12 08:40 UTC by Artsav23

2022-07-13 06:41 UTC, mokhaneugene commented
называй ветки с маленькой буквы

2022-07-13 06:58 UTC, mokhaneugene requested changes
не проверяешь сам себя, обсуждаем некоторые моменты, а ты все равно делаешь по-своему, пропускаешь пробелы, не думаешь над названиями

2022-07-13 06:58 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +        PublicationModel(R.drawable.ic_launcher_foreground, "4"),PublicationModel(R.drawable.ic_baseline_home_24, "5"),)
давай сделаем это более читаемым - сделай каждую модель с новой строчки

2022-07-13 06:58 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>          val view=LayoutInflater.from(parent.context).inflate(R.layout.view, parent, false)
не могу поставить комментарий ниже, но не суть: на 21 у тебя есть метод onBindViewHolder, он автоматически вызывается для каждого элемента

он будет вызываться столько раз, сколько в методе getItemCount() ты поставишь

получается что в методе onBindViewHolder ты можешь создать val publicationModel = publicationModels[position] и сделать holder.configure(model: publicationModel)

2022-07-13 06:58 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>          val view=LayoutInflater.from(parent.context).inflate(R.layout.view, parent, false)
в метода getItemCount() вместо publicationModel.size, лучше использовать publicationModel.count

2022-07-13 06:58 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>          val view=LayoutInflater.from(parent.context).inflate(R.layout.view, parent, false)
fun add может удалить пока

2022-07-13 06:58 UTC, mokhaneugene commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +    private var publicationModel = mutableListOf(PublicationModel(R.drawable.ic_add, "1"),
что такое publicationModel? у тебя же массив, назови publicationsModel, но опять же, у тебя массив моделей, а не массив публикаций, назову publicationModels

2022-07-13 13:01 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>          val view=LayoutInflater.from(parent.context).inflate(R.layout.view, parent, false)
я закомментировал

2022-07-13 13:04 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>          val view=LayoutInflater.from(parent.context).inflate(R.layout.view, parent, false)
done

2022-07-13 13:04 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +        PublicationModel(R.drawable.ic_launcher_foreground, "4"),PublicationModel(R.drawable.ic_baseline_home_24, "5"),)
done

2022-07-13 18:12 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +        PublicationModel(com.google.android.material.R.drawable.abc_btn_check_material, "3"),
так только можно обратится к картинке

2022-07-13 18:18 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
> +        PublicationModel( R.drawable.ic_message, "2"),
done

2022-07-13 18:18 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/Adapter.kt
>          val view=LayoutInflater.from(parent.context).inflate(R.layout.view, parent, false)
done

2022-07-15 08:36 UTC, mokhaneugene requested changes

2022-07-15 10:27 UTC, Artsav23 commented on app/src/main/java/com/example/socialnetwork/MainActivity.kt
>      private lateinit var launcher: ActivityResultLauncher<Intent>
no, i'm trying

2022-07-22 19:38 UTC, merged